language: node_js

sudo: false

node_js:  
      - 'stable'

install:
      - npm ci
      
env:
  - PORT=4000

notification:
          - email: false
script: 
      -npm test:coveralls
      -npm run coverage

